name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run golangci-lint
      # You may pin to the exact commit or the version.
      # uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        version: v1.42.1
        # if set to true then action uses pre-installed Go
        skip-go-installation: true

    - name: Build
      run: go build -v ./...

    - name: Lint
      run: golangci-lint run ./...

    - name: Test
      run: go test -v ./...
